version: '2'
services:
    cheaptransfert-app:
        image: cheaptransfert
        external_links:
            - cheaptransfert-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=cheaptransfert
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cheaptransfert-mongodb:
        extends:
            file: mongodb.yml
            service: cheaptransfert-mongodb
