version: '2'
services:
    cheaptransfert-mongodb:
        container_name: cheaptransfert-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/cheaptransfert/mongodb/:/data/db/
